### ISSUE TITLE
Updates to remove old TensorFlow V1 warnings

### ISSUE THREAD

**Issue by JKomp** [natschz/deepq#1]
I was wondering if you're interested in some updates to your code. I changed the following:

1) Removed most of the V1 deprecation warnings. There's one left.
2) Updated various argument lists to allow finer control of verbosity
3) Added a parameter to set a lower bound on epsilon so fit can terminate before all episodes are complete
4) Changed grid world to allow starting at a random location on each reset to better fill in the Q-Table
5) Added code to print out the Q-Table and the best action
6) Added attribution to your GitHub source

Thanks for providing the code. I'm looking to see if I can use it to learn a timed automaton. I'm not a TensorFlow guy by any means and this has help a lot.

**Comment by natschz** [comment]
Hey JKomp!

If you are still interested, just create a pull request.
I think it is a greate idea, to keep this up to date and/or improve on it, so others can benefit!

Also I'm glad to hear that it helped you!
